### ISSUE TITLE
Exkurs ES2015+ - fehlender Code?

### ISSUE THREAD

**Issue by alaskaa** [manuelbieh/react-lernen#27]
Vielleicht sehe ich es einfach wirklich nicht, aber ich glaube in dem Kapitel hier fehlt was im Code Beispiel zu Syntax-Erweiterungen und Vereinfachungen. Es geht um das zweite Beispiel, wo du einfach zweimal eine Variable mit const deklarierst, aber der console.log die dann zusammen ausgibt. Also um dieses hier:

const nationality = 'german';
const user = {
  name: 'Manuel',
};
console.log(user);
// -> { name: 'Manuel', german: true };

**Comment by manuelbieh** [comment]
Tatsächlich gut aufgepasst. Das hatte schon jemand angemerkt und einen PR gemacht den ich (eigentlich) gemerged hatte 🤔 
https://github.com/manuelbieh/react-lernen/pull/22

**Comment by alaskaa** [comment]
Hm, wie seltsam - eigentlich haette es das ja updaten muessen.

**Comment by manuelbieh** [comment]
Shit, irgendwie scheint Gitbook das nicht synchronisiert zu haben. Sehr sehr strange. Aber kacke, dann sind die ganzen anderen Änderungen von @martinborst die ich letzte Woche gemerged habe vermutlich auch nicht da. Muss ich mal checken und irgendwie dafür sorgen, dass die synchronisiert werden. Gut aufgepasst aber, danke! 🙂
